name: listener-ci

on:
  push:
    paths:
      - 'apps/listener/**'
      - '.github/workflows/listener-ci.yaml'
  pull_request:
    paths:
      - 'apps/listener/**'
      - '.github/workflows/listener-ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --manifest-path apps/listener/Cargo.toml
      - name: Build Docker
        run: docker build -t larptech/listener:latest apps/listener
